"""Provider-neutral production contracts."""

from .budget import (
    BudgetAuthorizationBoundary,
    BudgetAuthorizationRepository,
    BudgetAuthorizationRecord,
    BudgetDecisionOutcome,
    BudgetDecisionRecord,
    BudgetFailure,
    BudgetModule,
    PriceLineItem,
    PriceSnapshot,
    RetryPolicy,
)
from .sqlite_budget import SQLiteBudgetAuthorizationRepository
from .attempt import (
    ProviderAttemptClaim,
    ProviderAttemptFailure,
    ProviderAttemptLedger,
    ProviderAttemptOutcome,
    ProviderAttemptRecord,
    ProviderAttemptRepository,
    ProviderAttemptReservation,
)
from .sqlite_attempt import SQLiteProviderAttemptRepository
from .interfaces import LocalNarrationRenderer, MediaComposer, VisualGenerator, VoiceGenerator
from .model import (
    LocalNarrationPreflight,
    LocalNarrationResult,
    LocalNarrationTask,
    MediaCompositionResult,
    MediaCompositionScene,
    MediaCompositionTask,
    MediaGenerationResult,
    ProductionCompositionResult,
    ProductionExecutionResult,
    ProductionMediaFailure,
    VisualGenerationTask,
    VoiceSynthesisTask,
)
from .adapters import (
    DeterministicFakeVisualGenerator,
    DeterministicFakeVoiceGenerator,
    FFmpegMediaComposer,
    FFmpegFixtureVisualGenerator,
    FFmpegFixtureVoiceGenerator,
    LOCAL_IMPORTED_PROVIDER,
    LocalImportedPreflight,
    LocalImportedVisualGenerator,
    GPT_SOVITS_GPT_MODEL_BASENAME,
    GPT_SOVITS_INFERENCE_SCRIPT_BASENAME,
    GPT_SOVITS_MODEL_IDENTIFIER,
    GPT_SOVITS_PROVIDER,
    GPT_SOVITS_REFERENCE_PROVENANCE,
    GPT_SOVITS_REFERENCE_TRANSCRIPT,
    GPT_SOVITS_REPOSITORY_COMMIT,
    GPT_SOVITS_SOVITS_MODEL_BASENAME,
    GPTSoVITSConfiguration,
    GPTSoVITSPreflight,
    GPTSoVITSVoiceGenerator,
    GPTSoVITSSyntheticVoiceGenerator,
)
from .orchestrator import ProductionOrchestrator

__all__ = [
    "BudgetAuthorizationBoundary",
    "BudgetAuthorizationRepository",
    "BudgetAuthorizationRecord",
    "BudgetDecisionOutcome",
    "BudgetDecisionRecord",
    "BudgetFailure",
    "BudgetModule",
    "PriceLineItem",
    "PriceSnapshot",
    "RetryPolicy",
    "SQLiteBudgetAuthorizationRepository",
    "ProviderAttemptClaim",
    "ProviderAttemptFailure",
    "ProviderAttemptLedger",
    "ProviderAttemptOutcome",
    "ProviderAttemptRecord",
    "ProviderAttemptRepository",
    "ProviderAttemptReservation",
    "SQLiteProviderAttemptRepository",
    "MediaCompositionResult",
    "MediaCompositionScene",
    "MediaCompositionTask",
    "MediaComposer",
    "LocalNarrationPreflight",
    "LocalNarrationRenderer",
    "LocalNarrationResult",
    "LocalNarrationTask",
    "MediaGenerationResult",
    "ProductionCompositionResult",
    "ProductionExecutionResult",
    "ProductionMediaFailure",
    "VisualGenerationTask",
    "VoiceSynthesisTask",
    "VisualGenerator",
    "VoiceGenerator",
    "DeterministicFakeVisualGenerator",
    "DeterministicFakeVoiceGenerator",
    "FFmpegMediaComposer",
    "FFmpegFixtureVisualGenerator",
    "FFmpegFixtureVoiceGenerator",
    "LOCAL_IMPORTED_PROVIDER",
    "LocalImportedPreflight",
    "LocalImportedVisualGenerator",
    "GPT_SOVITS_PROVIDER",
    "GPT_SOVITS_MODEL_IDENTIFIER",
    "GPT_SOVITS_GPT_MODEL_BASENAME",
    "GPT_SOVITS_INFERENCE_SCRIPT_BASENAME",
    "GPT_SOVITS_SOVITS_MODEL_BASENAME",
    "GPT_SOVITS_REFERENCE_PROVENANCE",
    "GPT_SOVITS_REFERENCE_TRANSCRIPT",
    "GPT_SOVITS_REPOSITORY_COMMIT",
    "GPTSoVITSConfiguration",
    "GPTSoVITSPreflight",
    "GPTSoVITSVoiceGenerator",
    "GPTSoVITSSyntheticVoiceGenerator",
    "ProductionOrchestrator",
]
